// NF-4 中断復帰の E2E: (1) 完了後にリロード → 履歴から復元して出力数一致 (2) 処理途中でリロード → 中断として復元、処理済み分が残る
import { chromium } from 'playwright-core'
const [, , url, video, execPath] = process.argv
const browser = await chromium.launch({ headless: true, executablePath: execPath || undefined, args: ['--enable-features=WebCodecs', '--no-sandbox'] })
const ctx = await browser.newContext()
const page = await ctx.newPage()
page.on('pageerror', (e) => console.log('[pageerror]', e.message))
await page.goto(url)
await page.setInputFiles('#file', video)
await page.waitForFunction(() => ['完了', 'エラー'].includes(document.querySelector('#status').textContent), null, { timeout: 600_000 })
const n1 = await page.locator('#outputs figure').count()
console.log('run1 status', await page.textContent('#status'), 'outputs', n1)
// (1) リロードして復元
await page.reload()
await page.waitForSelector('.jobs li', { timeout: 30_000 })
console.log('jobs after reload:', await page.locator('.jobs li').allTextContents())
await page.locator('.jobs li button', { hasText: '結果を開く' }).first().click()
await page.waitForFunction((n) => document.querySelectorAll('#outputs figure').length === n, n1, { timeout: 30_000 })
const names = await page.locator('#outputs figure').evaluateAll((els) => els.map((e) => e.getAttribute('data-final')))
console.log('restored outputs', names.length, names.join(' '))
console.log('zip enabled after restore:', await page.locator('#zip').isEnabled())
// (2) 途中でリロード(クラッシュ相当)
await page.locator('.jobs li button', { hasText: '削除' }).first().click().catch(() => {})
page.once('dialog', (d) => d.accept())
await page.waitForTimeout(500)
await page.setInputFiles('#file', video)
await page.waitForFunction(() => document.querySelectorAll('#outputs figure').length >= 2, null, { timeout: 600_000 })
const partial = await page.locator('#outputs figure').count()
await page.reload()
await page.waitForSelector('.jobs li', { timeout: 30_000 })
const rows = await page.locator('.jobs li').allTextContents()
console.log('after crash-reload jobs:', rows)
await page.locator('.jobs li button', { hasText: '結果を開く' }).first().click()
await page.waitForFunction(() => document.querySelectorAll('#outputs figure').length >= 1, null, { timeout: 30_000 })
console.log('partial outputs before reload', partial, 'restored', await page.locator('#outputs figure').count(), 'status', await page.textContent('#status'))
await browser.close()
